void abertura();
void escolher_palavra();
void chutar(int *chutes_dados);
int verificar_chute(char letra);
int chutes_errados();
void desenhar_forca();
int enforcou();
int acertou();
void forca();
char resultado();
void adicionar_palavra();